all:
  vars:
    control_plane_endpoint: 10.10.1.10
    load_balancer_ip_pool:
      - 10.10.2.0/24
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 10.10.1.10, mac: '10:62:e5:11:b5:04', disk: nvme0n1, network_interface: eno1}
        metal1: {ansible_host: 10.10.1.11, mac: '10:62:e5:1a:c0:59', disk: nvme0n1, network_interface: eno1}
        metal2: {ansible_host: 10.10.1.12, mac: '10:62:e5:1a:67:8d', disk: nvme0n1, network_interface: eno1}
